### ISSUE TITLE
Implement std traits for Multimap and extend it

### ISSUE THREAD

**Issue by pyfisch** [havarnov/multimap#2]
Missing traits:
- [x] ::std::ops::Index (already implemented)
- [x] ::std::fmt::Debug #1
- [x] ::std::cmp::PartialEq #3
- [x] ::std::cmp::Eq #3
- [x] ::std::default::Default
- [x] ::std::iter::IntoIterator #4 
- [x] ::std::iter::FromIterator
- [x] ::std::iter::Extend

There are more functions not implemented for `MultiMap` which are implemented  for [`HashMap`](http://www.cplusplus.com/reference/map/multimap/) but they are useful here too. An example is the `values` function.

C++ also provides a [multimap](http://www.cplusplus.com/reference/map/multimap/) and maybe we can borrow some ideas from them. For example iterating over the values of a key would be useful.

There is also an issue to [add a multimap to rust](https://github.com/rust-lang/rfcs/issues/784).

**Comment by havarnov** [comment]
I agree that values could be useful, maybe open a new issue for that? We have to decide if the `.values()` returns a vector of vectors or just the first value in the value vectors.

**Comment by havarnov** [comment]
> For example iterating over the values of a key would be useful.

Isn't that already implemented for the `Vec` returned by `get_vec()`?
